In [120]:


def read_data(file_name: str) -> []:
    """
    Read data from a csv file.

    :param file_name: Name of the csv file.
    :return: A list of lists where each inner list represents a row from the csv file.
    """
    data = []
    with open(file_name, encoding="utf-8") as f:
        data = [line.strip().split(',') for line in f]

    return data

In [121]:
data = read_data("../resources/HW2_Sales_Data.csv")
category_ids = [ f"{i+1}" for i in range(7)]
get_category_data = lambda target: filter(lambda row: row[1] == target, data)
def extract_sales_data(rows:[]):
    order_ids = [int(row[0]) for row in rows]
    age = [int(row[2]) for row in rows]
    gender = [int(row[3]) for row in rows]
    return {"Order ID": order_ids, "Age": age, "Gender": gender}
Sales_data = {f"Category {category_id}": extract_sales_data(list(get_category_data(category_id))) for category_id in category_ids}
print(Sales_data)

{'Category 1': {'Order ID': [14, 18, 28, 33, 35, 38, 41, 47, 50], 'Age': [45, 55, 29, 25, 41, 64, 55, 36, 38], 'Gender': [1, 2, 1, 2, 1, 2, 2, 1, 1]}, 'Category 2': {'Order ID': [6, 27], 'Age': [44, 34], 'Gender': [2, 1]}, 'Category 3': {'Order ID': [1, 3, 9, 26, 37, 49], 'Age': [37, 30, 34, 27, 30, 25], 'Gender': [2, 2, 1, 2, 1, 2]}, 'Category 4': {'Order ID': [8, 11, 13, 15, 20, 32, 39, 44, 45, 46], 'Age': [61, 53, 30, 47, 54, 54, 34, 50, 35, 36], 'Gender': [1, 1, 2, 2, 2, 1, 1, 1, 1, 1]}, 'Category 5': {'Order ID': [2, 5, 7, 19, 23, 25, 42], 'Age': [47, 50, 48, 49, 50, 52, 25], 'Gender': [1, 2, 2, 1, 1, 1, 2]}, 'Category 6': {'Order ID': [4, 10, 17, 21, 22, 31, 34, 36], 'Age': [60, 50, 36, 36, 54, 38, 55, 56], 'Gender': [1, 2, 2, 2, 1, 2, 2, 1]}, 'Category 7': {'Order ID': [12, 16, 24, 29, 30, 40, 43, 48], 'Age': [23, 30, 47, 32, 46, 55, 20, 43], 'Gender': [1, 1, 2, 2, 2, 1, 1, 2]}}


In [122]:
category_data_count = {int(category_id): len(Sales_data[f"Category {category_id}"]["Order ID"]) for category_id in category_ids}
print(category_data_count)

{1: 9, 2: 2, 3: 6, 4: 10, 5: 7, 6: 8, 7: 8}


In [123]:
get_average_age = lambda age_data: sum(age_data) / len(age_data)
result = ""
for category_id, data in Sales_data.items():
    result += f"{category_id}: Average age = {get_average_age(data["Age"]):.2f}\n"
print(result)

Category 1: Average age = 43.11
Category 2: Average age = 39.00
Category 3: Average age = 30.50
Category 4: Average age = 45.40
Category 5: Average age = 45.86
Category 6: Average age = 48.12
Category 7: Average age = 37.00



In [124]:
import numpy as np
Car_Data = np.load("../resources/HW2_Car_Data.npy")
print(Car_Data[:5])


[[  122    84    26    32 11245]
 [  141   114    24    28 16515]
 [  110    56    34    36  7898]
 [  164   121    21    28 21105]
 [  110    86    27    33  8845]]


In [125]:
averages_by_columns = Car_Data.mean(axis=0)
result = f"""
Engine_size: {averages_by_columns[0]:.2f}
Horsepower: {averages_by_columns[1]:.2f}
City_mpg: {averages_by_columns[2]:.2f}
Highway_mpg: {averages_by_columns[3]:.2f}
Price: {averages_by_columns[4]:.2f}
"""
print(result)
averages_by_columns


Engine_size: 119.23
Horsepower: 95.84
City_mpg: 26.52
Highway_mpg: 32.08
Price: 11445.73



array([  119.22641509,    95.83647799,    26.52201258,    32.08176101,
       11445.72955975])

In [126]:
max_price =lambda inData: np.max(inData[: , -1])
min_price = lambda inData: np.min(inData[:,-1])

print(f"Max Price: {max_price(Car_Data)}")
print(f"Min Price: {min_price(Car_Data)}")


Max Price: 35056
Min Price: 5118


In [127]:
number_of_cars_above_average_engine_size = lambda inData: inData[ inData[: , 0] > averages_by_columns[0]].shape[0]


print(f"Number of cars with engine sizes above the average: {number_of_cars_above_average_engine_size(Car_Data)}")

Number of cars with engine sizes above the average: 69


In [128]:
IsAboveAverage  = Car_Data[: , 0] > averages_by_columns[0]
IsBelowAverage = ~IsAboveAverage
GetTotalHorsePower = lambda condition: Car_Data[condition, 1].sum()
TotalHorsePowerAboveAverage = GetTotalHorsePower(IsAboveAverage)
TotalHorsePowerBelowAverage = GetTotalHorsePower(IsBelowAverage)

print(f"Total Horse Power Above Average: {TotalHorsePowerAboveAverage}\nTotal Horse Power Below Average: {TotalHorsePowerBelowAverage}")


Total Horse Power Above Average: 8294
Total Horse Power Below Average: 6944


In [129]:
GetCarsAboveCityMPG = lambda mpg: Car_Data[: ,2] > mpg
GetCarsAboveHighwayMPG = lambda mpg: Car_Data[: , 3] > mpg
print(f"Total number of cars with city mpg above 35: {np.sum(GetCarsAboveCityMPG(35))}\n Total number of cars with highway mpg above 45: {np.sum(GetCarsAboveHighwayMPG(45))}")

Total number of cars with city mpg above 35: 14
 Total number of cars with highway mpg above 45: 7


In [130]:
#Data Analytics on DataFrame
def read_index(file_name: str) -> []:
    """
    Read data from a csv file.

    :param file_name: Name of the txt file.
    :return: A list of lists where each inner list represents a row from the txt file.
    """
    data = []
    with open(file_name, encoding="utf-8") as f:
        data = [line.strip().split(':')[0] for line in f]

    return data

column_names = read_index("../resources/HW2_Car_Index.txt")

In [131]:
import pandas as pd
def read_car_info(file_name: str)->pd.DataFrame:
    return pd.read_csv(file_name, header=None, names=column_names[:5])
df = read_car_info("../resources/HW2_Car_Info.csv")
df

Maker  Body_type Drivetrains Engine_type Num_of_cylinders
0     mazda  hatchback         fwd         ohc             four
1     volvo      wagon         rwd         ohc             four
2    toyota      sedan         fwd         ohc             four
3       bmw      sedan         rwd         ohc              six
4     honda      sedan         fwd         ohc             four
..      ...        ...         ...         ...              ...
154  toyota  hatchback         fwd         ohc             four
155   honda      sedan         fwd         ohc             four
156   volvo      sedan         rwd         ohc              six
157  toyota      sedan         rwd         ohc             four
158   volvo      sedan         rwd         ohc             four

[159 rows x 5 columns]

In [132]:
df2 = pd.DataFrame(Car_Data, columns=column_names[5:])
df2

Engine_size  Horsepower  City_mpg  Highway_mpg  Price
0            122          84        26           32  11245
1            141         114        24           28  16515
2            110          56        34           36   7898
3            164         121        21           28  21105
4            110          86        27           33   8845
..           ...         ...       ...          ...    ...
154           98          70        28           34   8358
155          110         101        24           28  12945
156          145         106        26           27  22470
157           98          70        29           34   8058
158          130         162        17           22  18420

[159 rows x 5 columns]

In [133]:
master_table = pd.concat([df, df2], axis=1)
master_table.index.name = "Sequence No"
master_table

Maker  Body_type Drivetrains Engine_type Num_of_cylinders  \
Sequence No                                                               
0             mazda  hatchback         fwd         ohc             four   
1             volvo      wagon         rwd         ohc             four   
2            toyota      sedan         fwd         ohc             four   
3               bmw      sedan         rwd         ohc              six   
4             honda      sedan         fwd         ohc             four   
...             ...        ...         ...         ...              ...   
154          toyota  hatchback         fwd         ohc             four   
155           honda      sedan         fwd         ohc             four   
156           volvo      sedan         rwd         ohc              six   
157          toyota      sedan         rwd         ohc             four   
158           volvo      sedan         rwd         ohc             four   

             Engine_size  Horsepower  City_mpg  Highway_mpg  Price  
Sequence No                                                         
0                    122          84        26           32  11245  
1                    141         114        24           28  16515  
2                    110          56        34           36   7898  
3                    164         121        21           28  21105  
4                    110          86        27           33   8845  
...                  ...         ...       ...          ...    ...  
154                   98          70        28           34   8358  
155                  110         101        24           28  12945  
156                  145         106        26           27  22470  
157                   98          70        29           34   8058  
158                  130         162        17           22  18420  

[159 rows x 10 columns]

In [134]:
master_table_description = master_table.describe()
price_stats = master_table_description.loc[["min", "max", "mean", "std"]]["Price"]
for index, price in price_stats.items():
    print(f"{index}: ${price:.2f}")

min: $5118.00
max: $35056.00
mean: $11445.73
std: $5877.86


In [135]:
def compute_stats(frame: pd.DataFrame)-> pd.DataFrame:
    return frame.describe().loc[["min", "max", "mean", "std"]]

compute_stats(master_table[column_names[6:-1]])

Horsepower   City_mpg  Highway_mpg
min    48.000000  15.000000    18.000000
max   200.000000  49.000000    54.000000
mean   95.836478  26.522013    32.081761
std    30.718583   6.097142     6.459189

In [136]:
master_table["H/E Ratio"]  = master_table["Horsepower"] / master_table["Engine_size"]
master_table

Maker  Body_type Drivetrains Engine_type Num_of_cylinders  \
Sequence No                                                               
0             mazda  hatchback         fwd         ohc             four   
1             volvo      wagon         rwd         ohc             four   
2            toyota      sedan         fwd         ohc             four   
3               bmw      sedan         rwd         ohc              six   
4             honda      sedan         fwd         ohc             four   
...             ...        ...         ...         ...              ...   
154          toyota  hatchback         fwd         ohc             four   
155           honda      sedan         fwd         ohc             four   
156           volvo      sedan         rwd         ohc              six   
157          toyota      sedan         rwd         ohc             four   
158           volvo      sedan         rwd         ohc             four   

             Engine_size  Horsepower  City_mpg  Highway_mpg  Price  H/E Ratio  
Sequence No                                                                    
0                    122          84        26           32  11245   0.688525  
1                    141         114        24           28  16515   0.808511  
2                    110          56        34           36   7898   0.509091  
3                    164         121        21           28  21105   0.737805  
4                    110          86        27           33   8845   0.781818  
...                  ...         ...       ...          ...    ...        ...  
154                   98          70        28           34   8358   0.714286  
155                  110         101        24           28  12945   0.918182  
156                  145         106        26           27  22470   0.731034  
157                   98          70        29           34   8058   0.714286  
158                  130         162        17           22  18420   1.246154  

[159 rows x 11 columns]

In [137]:
max_he = master_table["H/E Ratio"].idxmax()
min_he = master_table["H/E Ratio"].idxmin()
display_columns = ["H/E Ratio", "Maker", "Body_type"]

# master_table.loc[max_he, display_columns]
print(f"Car with Maximum H/E Ratio \n\n{master_table.loc[max_he, display_columns]}\n")
print(f"Car with Minimum H/E Ratio \n\n{master_table.loc[min_he, display_columns]}")


Car with Maximum H/E Ratio 

H/E Ratio     1.322314
Maker             saab
Body_type    hatchback
Name: 101, dtype: object

Car with Minimum H/E Ratio 

H/E Ratio    0.509091
Maker          toyota
Body_type       sedan
Name: 2, dtype: object


In [145]:
table_mask = (master_table["City_mpg"] > 32) & (master_table["Highway_mpg"] > 40)
# master_table[table_mask, ["Maker", "Price"]]
filtered_data = master_table[table_mask][["Maker", "Price"]]
filtered_data

Maker  Price
Sequence No                   
15               toyota   7738
25            chevrolet   6575
26               toyota   7788
60           volkswagen   9495
71           volkswagen   7775
78                dodge   5572
95           volkswagen   7995
99            chevrolet   6295
102           chevrolet   5151
106              nissan   7099
128          mitsubishi   5389
130               honda   6479
140               honda   5399
148            plymouth   5572

In [150]:
average_price = filtered_data["Price"].mean()
print(f"Average price: ${average_price:.2f}")

Average price: 6737.29


In [158]:
average_price_by_body_type = master_table.groupby("Body_type")["Price"].mean()
print(f"Average price by body type: \n{average_price_by_body_type.to_string(float_format="$%.2f")}")

Average price by body type: 
Body_type
convertible   $26362.50
hardtop       $13142.40
hatchback      $9220.16
sedan         $12558.62
wagon         $11351.41


In [86]:
"""
# The cells below are all test scripts to test the quality and functionality of the `read_data` function.
"""
def test_read_data():
    assert len(read_data("../resources/HW2_Sales_Data.csv")[1:]) == 50


In [88]:
test_read_data()