In [13]:
from unicodedata import category


def read_data(file_name: str) -> []:
    """
    Read data from a csv file.

    :param file_name: Name of the csv file.
    :return: A list of lists where each inner list represents a row from the csv file.
    """
    data = []
    with open(file_name, encoding="utf-8") as f:
        data = [line.strip().split(',') for line in f]

    return data


In [34]:
data = read_data("../resources/HW2_Sales_Data.csv")
category_ids = [ f"{i+1}" for i in range(7)]
get_category_data = lambda target: filter(lambda row: row[1] == target, data)
def extract_sales_data(rows:[]):
    order_ids = [int(row[0]) for row in rows]
    age = [int(row[2]) for row in rows]
    gender = [int(row[3]) for row in rows]
    return {"Order ID": order_ids, "Age": age, "Gender": gender}
Sales_data = {f"Category {category_id}": extract_sales_data(list(get_category_data(category_id))) for category_id in category_ids}
print(Sales_data)

{'Category 1': {'Order ID': [14, 18, 28, 33, 35, 38, 41, 47, 50], 'Age': [45, 55, 29, 25, 41, 64, 55, 36, 38], 'Gender': [1, 2, 1, 2, 1, 2, 2, 1, 1]}, 'Category 2': {'Order ID': [6, 27], 'Age': [44, 34], 'Gender': [2, 1]}, 'Category 3': {'Order ID': [1, 3, 9, 26, 37, 49], 'Age': [37, 30, 34, 27, 30, 25], 'Gender': [2, 2, 1, 2, 1, 2]}, 'Category 4': {'Order ID': [8, 11, 13, 15, 20, 32, 39, 44, 45, 46], 'Age': [61, 53, 30, 47, 54, 54, 34, 50, 35, 36], 'Gender': [1, 1, 2, 2, 2, 1, 1, 1, 1, 1]}, 'Category 5': {'Order ID': [2, 5, 7, 19, 23, 25, 42], 'Age': [47, 50, 48, 49, 50, 52, 25], 'Gender': [1, 2, 2, 1, 1, 1, 2]}, 'Category 6': {'Order ID': [4, 10, 17, 21, 22, 31, 34, 36], 'Age': [60, 50, 36, 36, 54, 38, 55, 56], 'Gender': [1, 2, 2, 2, 1, 2, 2, 1]}, 'Category 7': {'Order ID': [12, 16, 24, 29, 30, 40, 43, 48], 'Age': [23, 30, 47, 32, 46, 55, 20, 43], 'Gender': [1, 1, 2, 2, 2, 1, 1, 2]}}


In [33]:
category_data_count = {int(category_id): len(Sales_data[f"Category {category_id}"]["Order ID"]) for category_id in category_ids}
print(category_data_count)

{1: 9, 2: 2, 3: 6, 4: 10, 5: 7, 6: 8, 7: 8}


In [46]:
get_average_age = lambda age_data: sum(age_data) / len(age_data)
result = ""
for category_id, data in Sales_data.items():
    result += f"{category_id}: Average age = {get_average_age(data["Age"]):.2f}\n"
print(result)

Category 1: Average age = 43.11
Category 2: Average age = 39.00
Category 3: Average age = 30.50
Category 4: Average age = 45.40
Category 5: Average age = 45.86
Category 6: Average age = 48.12
Category 7: Average age = 37.00



In [9]:
import numpy as np
Car_Data = np.load("../resources/HW2_Car_Data.npy")
print(Car_Data[:5])

[[  122    84    26    32 11245]
 [  141   114    24    28 16515]
 [  110    56    34    36  7898]
 [  164   121    21    28 21105]
 [  110    86    27    33  8845]]


In [7]:
averages_by_columns = Car_Data.mean(axis=0)
result = f"""
Engine_size: {averages_by_columns[0]:.2f}
Horsepower: {averages_by_columns[1]:.2f}
City_mpg: {averages_by_columns[2]:.2f}
Highway_mpg: {averages_by_columns[3]:.2f}
Price: {averages_by_columns[4]:.2f}
"""
print(result)


Engine_size: 119.23
Horsepower: 95.84
City_mpg: 26.52
Highway_mpg: 32.08
Price: 11445.73



In [13]:
max_price =lambda inData: np.max(inData[: , -1])
min_price = lambda inData: np.min(inData[:,-1])

print(f"Max Price: {max_price(Car_Data)}")
print(f"Min Price: {min_price(Car_Data)}")


Max Price: 35056
Min Price: 5118


In [15]:
number_of_cars_above_average_engine_size = lambda inData: inData[ inData[: , 0] > averages_by_columns[0]].shape[0]


print(f"Number of cars with engine sizes above the average: {number_of_cars_above_average_engine_size(Car_Data)}")

Number of cars with engine sizes above the average: 69


In [15]:
"""
# The cells below are all test scripts to test the quality and functionality of the `read_data` function.
"""
def test_read_data():
    assert len(read_data("../resources/HW2_Sales_Data.csv")[1:]) == 50


In [16]:
test_read_data()